id: IF3ADEA26
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T13:44:06+00:00'
last_modified: '2022-06-08T09:00:23.637256+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG1390
  title: དགྱེས་པ་རྡོ་རྗེའི་རྒྱུད་གསུམ་གྱི་སྤྱི་དོན་སྔོན་འགྲོའི་ཚུལ་བཞིའི་གསལ་བྱེད་ལེགས་པར་བཤད་པ་ཉི་མའི་འོད་ཟེར་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5635':
      image_group_id: I1KG1393
      title: ''
      total_pages: 396
      order: 1
      base_file: 5635.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
