id: P009154
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:25:35.874831
source_metadata:
  id: bdr:W1KG1390
  title: དགྱེས་པ་རྡོ་རྗེའི་རྒྱུད་གསུམ་གྱི་སྤྱི་དོན་སྔོན་འགྲོའི་ཚུལ་བཞིའི་གསལ་བྱེད་ལེགས་པར་བཤད་པ་ཉི་མའི་འོད་ཟེར་
  author: ''
  volumes:
    5ba61d710d4f40a29334c50584f9cc04:
      image_group_id: I1KG1393
      title: ''
      volume_number: 1
      total_pages: 396
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
