id: P009154
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG1390
  title: དགྱེས་པ་རྡོ་རྗེའི་རྒྱུད་གསུམ་གྱི་སྤྱི་དོན་སྔོན་འགྲོའི་ཚུལ་བཞིའི་གསལ་བྱེད་ལེགས་པར་བཤད་པ་ཉི་མའི་འོད་ཟེར་
  author: ''
  volumes: {}
